name: Build and Release

on:
  push:
    branches:
      - main


jobs:

  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

  build:
    runs-on: ubuntu-latest
    needs: tag
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Install .net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "6.x"

    - name: Build and release
      run: |
        ./build.sh push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  